### ISSUE TITLE
WebUI look optimisation

### ISSUE THREAD

**Issue by Saentist** [proasnet/Axpertino#1]
I agree this is embedded project and every bit of data is important but,
see if this can optimise look of web page little bit.
https://github.com/you-dont-need/You-Dont-Need-JavaScript

**Comment by proasnet** [comment]
Yes, may be, but later. This is the first released version, with full funcionality. The web interface is designed mainly for network and connection settings, the main output is MQTT to Home Assistant. Design of web interface is not so important.
